name: Push Docker image and update Kustomize

on:
  push:
    branches:
      - "main"
      - "staging"
      - "dev"

    paths-ignore:
      - "*.md"
      - ".vscode/**"
concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push-to-docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> "$GITHUB_ENV"

      - name: Set env env_name
        run: |
          if [[ $BRANCH == 'main' ]]; then
              echo "env_name=prod" >> "$GITHUB_ENV"
          else
              echo env_name=$BRANCH >> "$GITHUB_ENV"
          fi

      - name: Echo environment
        run: echo $env_name

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |-
            ${{ secrets.DOCKER_USERNAME }}/rmq-test-nest-producer:latest
            ${{ secrets.DOCKER_USERNAME }}/rmq-test-nest-producer:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/rmq-test-nest-producer:${{ env.env_name }}

  update-kustomize-and-commit:
    name: Update Kustomize and commit changes
    runs-on: ubuntu-latest
    needs: build-and-push-to-docker

    steps:
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> "$GITHUB_ENV"

      - name: Set env env_name
        run: |
          if [[ $BRANCH == 'main' ]]; then
              echo "env_name=prod" >> "$GITHUB_ENV"
          else
              echo env_name=$BRANCH >> "$GITHUB_ENV"
          fi

      - name: Echo environment
        run: echo $env_name

      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: 5h4k4r/rmq-test-nest-producer-cd
          token: ${{ secrets.PAT }}
          ref: main

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.2.0"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo $env_name
          cd kubernetes/overlays/$env_name
          kustomize edit set image $DOCKER_USERNAME/rmq-test-nest-producer=$DOCKER_USERNAME/rmq-test-nest-producer:$GITHUB_SHA
          kustomize build
          cat kustomization.yaml

      - name: Commit files
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$DOCKER_USERNAME/rmq-test-nest-producer-cd
          git checkout main
          git commit -am "Bump docker tag"
          git push
